//! F6 goldens: images blit deterministically at NATURAL size (no scaling),
//! clipped to the widget rect, band-exactly, with integer source-over alpha
//! — and fail honestly (missing asset / missing src / junk registration),
//! never a blank box.
//!
//! The asset is the committed `tests/assets/checker-24.png` (generated by
//! `scripts/make-test-asset.py`): 4-colour checker, 1px border, transparent
//! centre hole, SEMI-TRANSPARENT bottom-right quadrant — decoded here with
//! the `png` crate (tests are std; core only ever sees RGBA bytes, I7).

use vyr_core::demo::{IMAGE_ASSET, IMAGE_IR};
use vyr_core::{Assets, Fonts, Rect, RenderError, RgbaImage, render, render_with};

const W: u32 = 120;
const H: u32 = 120;

/// Committed golden (FNV-1a 64). Re-bless: ./dev.py test --bless.
const IMAGE_GOLDEN_FNV1A: u64 = 0xE88D_53B6_4219_8019;

/// The shared F6 fixture (natural-size, clipped, over-frame and imagebutton
/// blits, all crossing band seams) — also what vyr-bench's image scene
/// measures.
const FIXTURE: &str = IMAGE_IR;

fn fnv1a(data: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x100_0000_01b3);
    }
    h
}

/// Decode the committed checker PNG into a registry under the fixture's
/// verbatim src name (the `assets` module name contract).
fn checker_assets() -> Assets {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/assets/checker-24.png");
    let file = std::fs::File::open(&path).expect("committed tests/assets/checker-24.png");
    let mut reader = png::Decoder::new(std::io::BufReader::new(file))
        .read_info()
        .expect("png header");
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("png decode");
    assert_eq!(info.color_type, png::ColorType::Rgba, "test asset is RGBA");
    buf.truncate(info.buffer_size());
    let img = RgbaImage::new(info.width, info.height, buf).expect("valid dims");
    assert_eq!((img.w(), img.h()), (24, 24), "test asset is 24x24");
    let mut assets = Assets::new();
    assets.register(IMAGE_ASSET, img).expect("register");
    assets
}

fn full(assets: &Assets) -> Vec<u8> {
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let stats = render_with(
        FIXTURE,
        &mut Fonts::new(),
        assets,
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect("image fixture renders");
    assert!(stats.pixels_written > 0);
    assert!(
        stats.pixels_by_class[vyr_core::OpClass::Blit as usize] > 0,
        "blit pixels counted into the Blit op class"
    );
    buf
}

fn dump_png(name: &str, buf: &[u8]) {
    if std::env::var_os("VYR_TEST_DUMP").is_none() {
        return;
    }
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../tmp");
    std::fs::create_dir_all(&dir).unwrap();
    let file = std::fs::File::create(dir.join(name)).unwrap();
    let mut enc = png::Encoder::new(std::io::BufWriter::new(file), W, H);
    enc.set_color(png::ColorType::Rgb);
    enc.set_depth(png::BitDepth::Eight);
    enc.write_header().unwrap().write_image_data(buf).unwrap();
}

fn px(buf: &[u8], x: u32, y: u32) -> [u8; 3] {
    let i = ((y * W + x) * 3) as usize;
    [buf[i], buf[i + 1], buf[i + 2]]
}

#[test]
fn image_golden_hash() {
    let buf = full(&checker_assets());
    dump_png("image-golden-f6.png", &buf);
    let h = fnv1a(&buf);
    if std::env::var_os("VYR_BLESS").is_some() {
        eprintln!("BLESS: IMAGE_GOLDEN_FNV1A = {h:#018X}");
        return;
    }
    assert_eq!(h, IMAGE_GOLDEN_FNV1A, "image golden drifted");
}

/// The exact integer source-over, spot-checked: the asset's SEMI-TRANSPARENT
/// quadrant (255,220,0,128) over the backdrop #3A6EA5 must blend to
/// round((s·a + d·(255−a))/255) per channel — and natural-size means the
/// widget area BEYOND the 24×24 asset stays pure backdrop (no scale-to-fit).
#[test]
fn image_blend_and_natural_size() {
    let buf = full(&checker_assets());
    // img1 at (12,14): image-local (16,16) = world (28,30) is inside the
    // semi-yellow BR quadrant. d = (58,110,165), s = (255,220,0), a = 128:
    // r = round((255·128 + 58·127)/255) = 157
    // g = round((220·128 + 110·127)/255) = 165
    // b = round((0·128 + 165·127)/255)  = 82
    assert_eq!(px(&buf, 28, 30), [157, 165, 82], "semi-alpha blend exact");
    // img1's widget rect is 40×40 but the asset is 24×24: (42,44) is inside
    // the widget, beyond the asset — pure backdrop (the no-resampling
    // policy; scale-to-fit would have painted here).
    assert_eq!(px(&buf, 42, 44), [58, 110, 165], "natural size, no scaling");
    // img2 at (70,50) is CLIPPED to a 16×12 widget: (87,55) is one column
    // right of the clip edge (the unclipped asset would reach x=94) — pure
    // backdrop again.
    assert_eq!(px(&buf, 87, 55), [58, 110, 165], "clipped to widget rect");
    // The transparent centre hole of img3 (56,80): local (11,11) = world
    // (67,91) shows the FRAME fill through (a==0 pixels are skipped).
    assert_eq!(px(&buf, 67, 91), [224, 216, 200], "a==0 skips, frame shows");
}

/// The F6 band-equivalence proof: blits crossing the band seams, stitched
/// from even (30) AND uneven (17) band heights, byte-identical to the full
/// frame — integer positions + deterministic integer blending (painter
/// docs), the glyph argument verbatim.
#[test]
fn image_band_equivalence() {
    let assets = checker_assets();
    let full = full(&assets);
    let stride = (W * 3) as usize;
    for band_h in [30u32, 17u32] {
        let mut banded = vec![0u8; stride * H as usize];
        let mut y = 0;
        while y < H {
            let h = band_h.min(H - y);
            let band = &mut banded[y as usize * stride..(y + h) as usize * stride];
            render_with(
                FIXTURE,
                &mut Fonts::new(),
                &assets,
                Rect {
                    x: 0,
                    y: y as i32,
                    w: W,
                    h,
                },
                band,
                stride,
            )
            .expect("band renders");
            y += h;
        }
        if full != banded {
            let diffs = full.iter().zip(&banded).filter(|(a, b)| a != b).count();
            dump_png(&format!("image-band-fail-full-{band_h}.png"), &full);
            dump_png(&format!("image-band-fail-banded-{band_h}.png"), &banded);
            panic!("band_h={band_h}: image band stitch differs ({diffs} bytes)");
        }
    }
}

/// Missing asset = hard error naming the request AND what IS registered
/// (I6: an unrenderable image errors before pixels, never a blank box).
#[test]
fn missing_asset_is_honest_error() {
    let ir = r#"{"w":120,"h":120,"root":{"name":"view","children":[
        {"name":"vy_image","attrs":{"x":"4","y":"4","width":"24","height":"24","src":"nope.png"}}]}}"#;
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let err = render_with(
        ir,
        &mut Fonts::new(),
        &checker_assets(),
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect_err("missing asset must hard-error");
    match err {
        RenderError::MissingAsset(msg) => {
            assert!(msg.contains("nope.png"), "names the request: {msg}");
            assert!(msg.contains("checker-24.png"), "names available: {msg}");
        }
        other => panic!("expected MissingAsset, got {other:?}"),
    }
}

/// vy_image with NO src attr = BadIr (junk IR, not an empty box).
#[test]
fn image_without_src_is_bad_ir() {
    let ir = r#"{"w":120,"h":120,"root":{"name":"view","children":[
        {"name":"vy_image","attrs":{"name":"img0","x":"4","y":"4","width":"24","height":"24"}}]}}"#;
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let err = render_with(
        ir,
        &mut Fonts::new(),
        &checker_assets(),
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect_err("src-less image must hard-error");
    match err {
        RenderError::BadIr(msg) => {
            assert!(msg.contains("src"), "names the missing attr: {msg}");
            assert!(msg.contains("img0"), "names the node: {msg}");
        }
        other => panic!("expected BadIr, got {other:?}"),
    }
}

/// The assets-less `render()` convenience stays honest: image IR through it
/// is a MissingAsset error (there is nothing to blit), never a blank.
#[test]
fn render_without_assets_is_honest_error() {
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let err = render(
        FIXTURE,
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect_err("no assets registered → image must hard-error");
    assert!(matches!(err, RenderError::MissingAsset(_)), "{err:?}");
}

/// Registration honesty: byte count must match the claimed dimensions, and
/// duplicate names are rejected — caught at register time, never mid-blit.
#[test]
fn registry_rejects_junk() {
    let err = RgbaImage::new(24, 24, vec![0u8; 7]).expect_err("wrong byte count");
    assert!(matches!(err, RenderError::BadAsset(_)), "{err:?}");
    let err = RgbaImage::new(0, 24, Vec::new()).expect_err("zero dimension");
    assert!(matches!(err, RenderError::BadAsset(_)), "{err:?}");
    let mut assets = Assets::new();
    let img = || RgbaImage::new(2, 2, vec![0u8; 16]).expect("valid");
    assets.register("twice.png", img()).expect("first ok");
    let err = assets
        .register("twice.png", img())
        .expect_err("duplicate name");
    assert!(matches!(err, RenderError::BadAsset(_)), "{err:?}");
}
