//! F6 goldens: images draw deterministically FIT-TO-CELL (scaled to fit inside
//! the widget rect preserving aspect, centred, letterboxed — Qt is the locked
//! reference, #325/#6), band-exactly, with NEAREST-NEIGHBOUR fixed-point
//! resampling + integer source-over alpha — and fail honestly (missing asset /
//! missing src / junk registration), never a blank box.
//!
//! The asset is the committed `tests/assets/checker-24.png` (generated by
//! `scripts/make-test-asset.py`): 4-colour checker, 1px border, transparent
//! centre hole, SEMI-TRANSPARENT bottom-right quadrant — decoded here with
//! the `png` crate (tests are std; core only ever sees RGBA bytes, I7).

use vyr_core::demo::{IMAGE_ASSET, IMAGE_IR};
use vyr_core::{Assets, Fonts, Rect, RenderError, RgbaImage, render, render_with};

const W: u32 = 120;
const H: u32 = 120;

/// Committed golden (FNV-1a 64). Re-bless: ./dev.py test --bless.
/// 2026-06-12: re-blessed for FIT-TO-CELL (#6/#325) — was natural-size top-left;
/// now scaled-to-fit, aspect-preserved, centred, letterboxed (read the dumped
/// PNG: img1 fills its square box, img2/imagebutton show backdrop letterbox
/// bands, img3 is 1:1 — correct).
const IMAGE_GOLDEN_FNV1A: u64 = 0xCDBB_2B43_0E86_BC2A;

/// The shared F6 fixture (fit-to-cell into widget boxes of varied aspect —
/// square-into-square, wide-box letterbox, 1:1, over-frame and imagebutton —
/// all crossing band seams) — also what vyr-bench's image scene measures.
const FIXTURE: &str = IMAGE_IR;

fn fnv1a(data: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x100_0000_01b3);
    }
    h
}

/// Decode the committed checker PNG into a registry under the fixture's
/// verbatim src name (the `assets` module name contract).
fn checker_assets() -> Assets {
    let mut reader = png::Decoder::new(std::io::Cursor::new(include_bytes!(
        "assets/checker-24.png"
    )))
    .read_info()
    .expect("png header");
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("png decode");
    assert_eq!(info.color_type, png::ColorType::Rgba, "test asset is RGBA");
    buf.truncate(info.buffer_size());
    let img = RgbaImage::new(info.width, info.height, buf).expect("valid dims");
    assert_eq!((img.w(), img.h()), (24, 24), "test asset is 24x24");
    let mut assets = Assets::new();
    assets.register(IMAGE_ASSET, img).expect("register");
    assets
}

fn full(assets: &Assets) -> Vec<u8> {
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let stats = render_with(
        FIXTURE,
        &mut Fonts::new(),
        assets,
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect("image fixture renders");
    assert!(stats.pixels_written > 0);
    assert!(
        stats.pixels_by_class[vyr_core::OpClass::Blit as usize] > 0,
        "blit pixels counted into the Blit op class"
    );
    buf
}

fn dump_png(name: &str, buf: &[u8]) {
    if std::env::var_os("VYR_TEST_DUMP").is_none() {
        return;
    }
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../tmp");
    std::fs::create_dir_all(&dir).unwrap();
    let file = std::fs::File::create(dir.join(name)).unwrap();
    let mut enc = png::Encoder::new(std::io::BufWriter::new(file), W, H);
    enc.set_color(png::ColorType::Rgb);
    enc.set_depth(png::BitDepth::Eight);
    enc.write_header().unwrap().write_image_data(buf).unwrap();
}

fn px(buf: &[u8], x: u32, y: u32) -> [u8; 3] {
    let i = ((y * W + x) * 3) as usize;
    [buf[i], buf[i + 1], buf[i + 2]]
}

#[test]
fn image_golden_hash() {
    let buf = full(&checker_assets());
    dump_png("image-golden-f6.png", &buf);
    let h = fnv1a(&buf);
    if std::env::var_os("VYR_BLESS").is_some() {
        eprintln!("BLESS: IMAGE_GOLDEN_FNV1A = {h:#018X}");
        return;
    }
    assert_eq!(h, IMAGE_GOLDEN_FNV1A, "image golden drifted");
}

/// FIT-TO-CELL geometry + exact integer source-over, spot-checked (Qt is the
/// locked reference: scale=min(bw/W,bh/H), centred, letterboxed). The blit now
/// SCALES, so source pixels are mapped by nearest-neighbour fixed-point
/// integer math (`sx = (wx-dst.x)·W/dst.w`); the alpha-blend spot follows the
/// fitted position.
#[test]
fn image_blend_fit_to_cell() {
    let buf = full(&checker_assets());
    // img1 box (12,14,40,40), asset 24×24 → scale 40/24, dest 40×40 at (12,14)
    // FILLS the box (square asset into square box, no letterbox). World (40,42)
    // maps to src col ((40-12)·24)/40 = 16, src row ((42-14)·24)/40 = 16 — the
    // semi-yellow BR quadrant (255,220,0,128) over backdrop #3A6EA5 (58,110,
    // 165): r=round((255·128+58·127)/255)=157, g=165, b=round((165·127)/255)=82.
    assert_eq!(px(&buf, 40, 42), [157, 165, 82], "semi-alpha blend at fit");
    // img2 box (70,50,16,12), asset 24×24 → scale min(16/24,12/24)=0.5,
    // dest 12×12 centred at (72,50): LETTERBOX bands at x∈[70,72) and [84,86).
    // World (70,55) is in the left letterbox — pure backdrop shows through
    // (fit-to-cell paints NOTHING in the bands; natural-size would have here).
    assert_eq!(px(&buf, 70, 55), [58, 110, 165], "letterbox shows backdrop");
    // World (74,55) is inside the centred dest: src col ((74-72)·24)/12 = 4,
    // src row ((55-50)·24)/12 = 10 → the opaque TL red quadrant (230,40,40),
    // landing where natural-size/no-fit would not have. Guards against both
    // the image vanishing AND a wrong (un-centred) dest.
    assert_eq!(
        px(&buf, 74, 55),
        [230, 40, 40],
        "fitted+centred image painted"
    );
    // img3 box (56,80,24,24), asset 24×24 → scale 1.0, dest 24×24 at (56,80)
    // (1:1). The transparent centre hole src (11,11) = world (67,91) shows the
    // FRAME fill through (a==0 pixels are skipped).
    assert_eq!(px(&buf, 67, 91), [224, 216, 200], "a==0 skips, frame shows");
}

/// The F6 band-equivalence proof: fit-to-cell blits (up- AND down-scaled)
/// crossing the band seams, stitched from even (30) AND uneven (17) band
/// heights, byte-identical to the full frame — the nearest-neighbour source
/// map is a pure integer function of WORLD position (painter docs), so it is
/// band-invariant by the same induction as the 1:1 blit.
#[test]
fn image_band_equivalence() {
    let assets = checker_assets();
    let full = full(&assets);
    let stride = (W * 3) as usize;
    for band_h in [30u32, 17u32] {
        let mut banded = vec![0u8; stride * H as usize];
        let mut y = 0;
        while y < H {
            let h = band_h.min(H - y);
            let band = &mut banded[y as usize * stride..(y + h) as usize * stride];
            render_with(
                FIXTURE,
                &mut Fonts::new(),
                &assets,
                Rect {
                    x: 0,
                    y: y as i32,
                    w: W,
                    h,
                },
                band,
                stride,
            )
            .expect("band renders");
            y += h;
        }
        if full != banded {
            let diffs = full.iter().zip(&banded).filter(|(a, b)| a != b).count();
            dump_png(&format!("image-band-fail-full-{band_h}.png"), &full);
            dump_png(&format!("image-band-fail-banded-{band_h}.png"), &banded);
            panic!("band_h={band_h}: image band stitch differs ({diffs} bytes)");
        }
    }
}

/// Band-equivalence for an AGGRESSIVELY SCALED image: the 24×24 asset
/// UPSCALED ~4× into an 88×100 box (non-uniform aspect → distinct x/y scales)
/// that crosses MANY band seams, plus a 16×16 DOWNSCALE box, stitched at FIVE
/// band heights — even divisors (20, 24, 40) AND uneven non-divisors (7, 13).
/// Proves the nearest-neighbour fixed-point source map (`sx = (wx-dst.x)·W/dst.w`,
/// integer division) stays byte-exact across seams: it is a pure integer
/// function of WORLD position, so every band maps a given world pixel to the
/// SAME source pixel — band-invariant by the same induction as the 1:1 blit.
/// (A float source map, or one keyed off band-local row, would diverge here.)
#[test]
fn scaled_image_band_equivalence() {
    // 88/24 ≈ 3.67 and 100/24 ≈ 4.17 are independent non-integer scales, so
    // the x and y source maps step at different rates — the worst case for a
    // sloppy (band-local or float) resampler. The downscale box adds the other
    // direction. Both cross the 120×120 frame's seams.
    const SCALE_IR: &str = r##"{"w":120,"h":120,
      "root":{"name":"view","attrs":{"background":"#3A6EA5"},"children":[
        {"name":"vy_image","attrs":{"x":"8","y":"6","width":"88","height":"100",
          "src":"checker-24.png"}},
        {"name":"vy_image","attrs":{"x":"100","y":"4","width":"16","height":"16",
          "src":"checker-24.png"}}
      ]}}"##;
    let assets = checker_assets();
    let stride = (W * 3) as usize;
    let mut full = vec![0u8; stride * H as usize];
    render_with(
        SCALE_IR,
        &mut Fonts::new(),
        &assets,
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut full,
        stride,
    )
    .expect("scaled image full-frame renders");
    for band_h in [20u32, 24u32, 40u32, 7u32, 13u32] {
        let mut banded = vec![0u8; stride * H as usize];
        let mut y = 0;
        while y < H {
            let h = band_h.min(H - y);
            let band = &mut banded[y as usize * stride..(y + h) as usize * stride];
            render_with(
                SCALE_IR,
                &mut Fonts::new(),
                &assets,
                Rect {
                    x: 0,
                    y: y as i32,
                    w: W,
                    h,
                },
                band,
                stride,
            )
            .expect("scaled image band renders");
            y += h;
        }
        if full != banded {
            let diffs = full.iter().zip(&banded).filter(|(a, b)| a != b).count();
            dump_png(&format!("scaled-band-fail-full-{band_h}.png"), &full);
            dump_png(&format!("scaled-band-fail-banded-{band_h}.png"), &banded);
            panic!("band_h={band_h}: scaled image band stitch differs ({diffs} bytes)");
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────
// F6 object-fit: the SAME 24×24 asset in all FIVE CSS fit modes, side by side.
// ──────────────────────────────────────────────────────────────────────────

/// Five 20-px-wide × 100-px-tall boxes (deliberately non-square so the modes
/// VISIBLY differ — a square asset into a tall box letterboxes for contain,
/// crops for cover, stretches for fill) over a coloured backdrop. One box per
/// mode, left→right: contain / cover / none / fill / scale-down.
///
/// Asset 24×24, box 20×100:
/// - **contain**: scale=min(20/24,100/24)=0.833 → 20×20, centred → letterbox
///   top+bottom (the backdrop shows in the bands).
/// - **cover**: scale=max(20/24,100/24)=4.167 → 100×100, centred NEGATIVE in x
///   (x = bx+(20-100)/2 = bx-40) → fills the 20×100 box, sides CROPPED.
/// - **none**: natural 24×24, centred → 2px overflow each side in x (cropped),
///   big letterbox top+bottom in y.
/// - **fill**: 20×100 exactly — stretched, aspect broken.
/// - **scale-down**: min(1.0, contain 0.833)=0.833 → SAME as contain here (the
///   asset DOWN-scales to fit; it never exceeds the box, so scale-down picks
///   contain, not natural).
const FIT_IR: &str = r##"{"w":120,"h":120,
  "root":{"name":"view","attrs":{"background":"#3A6EA5"},"children":[
    {"name":"vy_image","attrs":{"x":"2","y":"10","width":"20","height":"100",
      "src":"checker-24.png","fit":"contain"}},
    {"name":"vy_image","attrs":{"x":"26","y":"10","width":"20","height":"100",
      "src":"checker-24.png","fit":"cover"}},
    {"name":"vy_image","attrs":{"x":"50","y":"10","width":"20","height":"100",
      "src":"checker-24.png","fit":"none"}},
    {"name":"vy_image","attrs":{"x":"74","y":"10","width":"20","height":"100",
      "src":"checker-24.png","fit":"fill"}},
    {"name":"vy_image","attrs":{"x":"98","y":"10","width":"20","height":"100",
      "src":"checker-24.png","fit":"scale-down"}}
  ]}}"##;

/// Committed object-fit golden (FNV-1a 64). Re-bless: ./dev.py test --bless.
/// 2026-06-12: blessed for tunable CSS object-fit (#6/#325) — read the dumped
/// PNG: contain box letterboxes (backdrop top/bottom), cover FILLS+crops, none
/// is natural-centred (small, big top/bottom letterbox), fill is STRETCHED tall,
/// scale-down == contain (asset down-scales). All five visibly differ.
const FIT_GOLDEN_FNV1A: u64 = 0x2D1E_4628_AFAD_861B;

fn fit_full() -> Vec<u8> {
    let assets = checker_assets();
    let mut buf = vec![0u8; (W * H * 3) as usize];
    render_with(
        FIT_IR,
        &mut Fonts::new(),
        &assets,
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect("object-fit fixture renders");
    buf
}

#[test]
fn object_fit_golden_hash() {
    let buf = fit_full();
    dump_png("object-fit-f6.png", &buf);
    let h = fnv1a(&buf);
    if std::env::var_os("VYR_BLESS").is_some() {
        eprintln!("BLESS: FIT_GOLDEN_FNV1A = {h:#018X}");
        return;
    }
    assert_eq!(h, FIT_GOLDEN_FNV1A, "object-fit golden drifted");
}

/// Each mode geometry, spot-checked against the dest-rect formula. The 24×24
/// checker has an opaque TL red quadrant (230,40,40), opaque quadrant fills,
/// a 1px near-black border (20,20,20) and a TRANSPARENT centre hole — so the
/// dst CENTRE shows the backdrop through; the assertions sample OPAQUE
/// quadrant points, not the hole. Backdrop is #3A6EA5 (58,110,165). Every box
/// is 20×100, y-band [10,110).
#[test]
fn object_fit_modes_differ() {
    let buf = fit_full();
    const BG: [u8; 3] = [58, 110, 165];
    // CONTAIN box (2,10,20,100): scale=min(20/24,100/24)=0.833 → dst 20×20
    // centred y∈[50,70), x∈[2,22). LETTERBOX top/bottom.
    assert_eq!(px(&buf, 12, 20), BG, "contain letterboxes top");
    assert_eq!(px(&buf, 12, 100), BG, "contain letterboxes bottom");
    // Opaque TL red quadrant: wx=6 → sx=(4·24)/20=4, wy=54 → sy=(4·24)/20=4.
    assert_eq!(
        px(&buf, 6, 54),
        [230, 40, 40],
        "contain paints the TL quadrant"
    );
    // COVER box (26,10,20,100): scale=max(20/24,100/24)=4.167 → dst 100×100 at
    // x=-14,y=10 → FILLS the full box height [10,110), clipped to x∈[26,46).
    // NO letterbox top/bottom (the proof cover differs from contain).
    assert_ne!(px(&buf, 36, 14), BG, "cover fills the top (no letterbox)");
    assert_ne!(
        px(&buf, 36, 105),
        BG,
        "cover fills the bottom (no letterbox)"
    );
    // NONE box (50,10,20,100): natural 24×24 centred y∈[48,72), x∈[48,72)
    // clipped to the box [50,70). Big letterbox top/bottom (24 ≪ 100).
    assert_eq!(
        px(&buf, 60, 20),
        BG,
        "none letterboxes top (natural is small)"
    );
    // 1:1 src map: wx=53 → sx=53-48=5, wy=53 → sy=53-48=5 → TL red quadrant.
    assert_eq!(
        px(&buf, 53, 53),
        [230, 40, 40],
        "none paints natural-size 1:1"
    );
    // FILL box (74,10,20,100): stretched to fill — top AND bottom are image
    // (the asset's first/last rows stretched), no letterbox anywhere.
    assert_ne!(px(&buf, 84, 14), BG, "fill stretches to the top");
    assert_ne!(px(&buf, 84, 105), BG, "fill stretches to the bottom");
    // SCALE-DOWN box (98,10,20,100): asset 24>20 DOWN-scales → == contain (dst
    // 20×20 centred y∈[50,70)). Letterboxed like contain (NOT natural-centred
    // like none) — proves scale-down picked min(1.0, contain)=contain.
    assert_eq!(px(&buf, 108, 20), BG, "scale-down letterboxes (== contain)");
    assert_eq!(
        px(&buf, 102, 54),
        [230, 40, 40],
        "scale-down paints the TL quadrant (fitted like contain)"
    );
}

/// Band-equivalence for the OVERFLOW (cover) + NON-UNIFORM (fill) cases — the
/// dst rects that exceed the box / break aspect, the worst case for a sloppy
/// resampler. Stitched at EVEN (20, 25, 40) AND UNEVEN (7, 13) band heights,
/// byte-identical to the full frame: the nearest source map is a pure integer
/// function of WORLD position + the band-invariant dst, so cover's negative
/// dst.x and fill's distinct x/y scales map every world pixel to the same src
/// in every band.
#[test]
fn object_fit_band_equivalence() {
    let assets = checker_assets();
    let stride = (W * 3) as usize;
    let full = fit_full();
    for band_h in [20u32, 25u32, 40u32, 7u32, 13u32] {
        let mut banded = vec![0u8; stride * H as usize];
        let mut y = 0;
        while y < H {
            let h = band_h.min(H - y);
            let band = &mut banded[y as usize * stride..(y + h) as usize * stride];
            render_with(
                FIT_IR,
                &mut Fonts::new(),
                &assets,
                Rect {
                    x: 0,
                    y: y as i32,
                    w: W,
                    h,
                },
                band,
                stride,
            )
            .expect("object-fit band renders");
            y += h;
        }
        if full != banded {
            let diffs = full.iter().zip(&banded).filter(|(a, b)| a != b).count();
            dump_png(&format!("object-fit-band-fail-full-{band_h}.png"), &full);
            dump_png(
                &format!("object-fit-band-fail-banded-{band_h}.png"),
                &banded,
            );
            panic!("band_h={band_h}: object-fit band stitch differs ({diffs} bytes)");
        }
    }
}

/// An UNKNOWN `fit` value = hard `BadIr` naming the accepted set (I6 — never
/// silently default to contain on junk IR).
#[test]
fn unknown_fit_is_bad_ir() {
    let ir = r#"{"w":120,"h":120,"root":{"name":"view","children":[
        {"name":"vy_image","attrs":{"x":"4","y":"4","width":"24","height":"24",
          "src":"checker-24.png","fit":"bogus"}}]}}"#;
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let err = render_with(
        ir,
        &mut Fonts::new(),
        &checker_assets(),
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect_err("unknown fit must hard-error");
    match err {
        RenderError::BadIr(msg) => {
            assert!(msg.contains("bogus"), "names the bad value: {msg}");
            assert!(msg.contains("contain"), "names the accepted set: {msg}");
            assert!(msg.contains("scale-down"), "names the accepted set: {msg}");
        }
        other => panic!("expected BadIr, got {other:?}"),
    }
}

/// Missing asset = hard error naming the request AND what IS registered
/// (I6: an unrenderable image errors before pixels, never a blank box).
#[test]
fn missing_asset_is_honest_error() {
    let ir = r#"{"w":120,"h":120,"root":{"name":"view","children":[
        {"name":"vy_image","attrs":{"x":"4","y":"4","width":"24","height":"24","src":"nope.png"}}]}}"#;
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let err = render_with(
        ir,
        &mut Fonts::new(),
        &checker_assets(),
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect_err("missing asset must hard-error");
    match err {
        RenderError::MissingAsset(msg) => {
            assert!(msg.contains("nope.png"), "names the request: {msg}");
            assert!(msg.contains("checker-24.png"), "names available: {msg}");
        }
        other => panic!("expected MissingAsset, got {other:?}"),
    }
}

/// vy_image with NO src attr = BadIr (junk IR, not an empty box).
#[test]
fn image_without_src_is_bad_ir() {
    let ir = r#"{"w":120,"h":120,"root":{"name":"view","children":[
        {"name":"vy_image","attrs":{"name":"img0","x":"4","y":"4","width":"24","height":"24"}}]}}"#;
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let err = render_with(
        ir,
        &mut Fonts::new(),
        &checker_assets(),
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect_err("src-less image must hard-error");
    match err {
        RenderError::BadIr(msg) => {
            assert!(msg.contains("src"), "names the missing attr: {msg}");
            assert!(msg.contains("img0"), "names the node: {msg}");
        }
        other => panic!("expected BadIr, got {other:?}"),
    }
}

/// The assets-less `render()` convenience stays honest: image IR through it
/// is a MissingAsset error (there is nothing to blit), never a blank.
#[test]
fn render_without_assets_is_honest_error() {
    let mut buf = vec![0u8; (W * H * 3) as usize];
    let err = render(
        FIXTURE,
        Rect {
            x: 0,
            y: 0,
            w: W,
            h: H,
        },
        &mut buf,
        (W * 3) as usize,
    )
    .expect_err("no assets registered → image must hard-error");
    assert!(matches!(err, RenderError::MissingAsset(_)), "{err:?}");
}

/// Registration honesty: byte count must match the claimed dimensions, and
/// duplicate names are rejected — caught at register time, never mid-blit.
#[test]
fn registry_rejects_junk() {
    let err = RgbaImage::new(24, 24, vec![0u8; 7]).expect_err("wrong byte count");
    assert!(matches!(err, RenderError::BadAsset(_)), "{err:?}");
    let err = RgbaImage::new(0, 24, Vec::new()).expect_err("zero dimension");
    assert!(matches!(err, RenderError::BadAsset(_)), "{err:?}");
    let mut assets = Assets::new();
    let img = || RgbaImage::new(2, 2, vec![0u8; 16]).expect("valid");
    assets.register("twice.png", img()).expect("first ok");
    let err = assets
        .register("twice.png", img())
        .expect_err("duplicate name");
    assert!(matches!(err, RenderError::BadAsset(_)), "{err:?}");
}
